DROP DATABASE IF EXISTS userdatabase;
CREATE DATABASE userdatabase;
USE userdatabase;
DROP TABLE IF EXISTS USER_DATA;
CREATE TABLE USER_DATA (
 USER_ID varchar(40) NOT NULL,
 USER_NAME varchar(100) NOT NULL,
 USER_EMAIL varchar(255) NOT NULL,
 USER_PASS varchar(40) NOT NULL,
 LAST_LOGIN_DATA DATETIME NULL,
 CREATED_BY varchar(100) NOT NULL,
 CREATED_AT DATETIME NOT NULL,
 UPDATED_BY varchar(100)  NULL,
 UPDATED_AT DATETIME  NULL,
 CONSTRAINT USER_DATA_PK PRIMARY KEY (USER_ID)
 );